"""create statistics table

Revision ID: f123456789ab
Revises: e9131814a862
Create Date: 2025-10-09 22:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f123456789ab'
down_revision: Union[str, None] = 'e9131814a862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statistics',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('outcome_id', sa.BigInteger(), nullable=False),
    sa.Column('prediction_id', sa.BigInteger(), nullable=True),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('championship_id', sa.BigInteger(), nullable=False),
    sa.Column('sport_id', sa.BigInteger(), nullable=False),
    sa.Column('match_date', sa.DATE(), nullable=False),
    sa.Column('match_round', sa.VARCHAR(length=50), nullable=True),
    sa.Column('match_stage', sa.VARCHAR(length=50), nullable=True),
    sa.Column('forecast_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('forecast_subtype', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('model_version', sa.VARCHAR(length=20), nullable=True),
    sa.Column('model_type', sa.VARCHAR(length=20), nullable=True),
    sa.Column('actual_result', sa.VARCHAR(length=50), nullable=True),
    sa.Column('actual_value', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('prediction_correct', sa.BOOLEAN(), nullable=True),
    sa.Column('prediction_accuracy', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('prediction_error', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('prediction_residual', sa.Numeric(precision=10, scale=3), nullable=True),
    sa.Column('coefficient', sa.Numeric(precision=8, scale=3), nullable=True),
    sa.Column('potential_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('actual_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['championship_id'], ['championships.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['match_id'], ['matchs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['outcome_id'], ['outcomes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prediction_id'], ['predictions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sport_id'], ['sports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_championship_id'), 'statistics', ['championship_id'], unique=False)
    op.create_index(op.f('ix_statistics_forecast_type'), 'statistics', ['forecast_type'], unique=False)
    op.create_index(op.f('ix_statistics_match_date'), 'statistics', ['match_date'], unique=False)
    op.create_index(op.f('ix_statistics_match_id'), 'statistics', ['match_id'], unique=False)
    op.create_index(op.f('ix_statistics_model_name'), 'statistics', ['model_name'], unique=False)
    op.create_index(op.f('ix_statistics_outcome_id'), 'statistics', ['outcome_id'], unique=False)
    op.create_index(op.f('ix_statistics_prediction_correct'), 'statistics', ['prediction_correct'], unique=False)
    op.create_index(op.f('ix_statistics_prediction_id'), 'statistics', ['prediction_id'], unique=False)
    op.create_index(op.f('ix_statistics_sport_id'), 'statistics', ['sport_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_statistics_sport_id'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_prediction_id'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_prediction_correct'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_outcome_id'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_model_name'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_match_id'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_match_date'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_forecast_type'), table_name='statistics')
    op.drop_index(op.f('ix_statistics_championship_id'), table_name='statistics')
    op.drop_table('statistics')
    # ### end Alembic commands ###
