name: Python CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 . --exclude=__pycache__,venv

      - name: Format check with Black
        run: |
          black --check .

      - name: Run pytest
        run: |
          pytest tests/ --cov=.

      - name: Upload coverage to Codecov (optional)
        if: success()
        uses: codecov/codecov-action@v3

      - name: Run calculation.py
        run: |
          python calculation.py current

      - name: Build Docker image
        run: |
          docker build -t football-tournament:latest .
